name: Update

on:
  workflow_dispatch:
  schedule: [{ cron: '0 0 * * 0' }]

jobs:
  update:
    name: Maintain
    uses: luisfalconmx/.github/.github/workflows/update.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
